apiVersion: v1
kind: Service
metadata:
  name: habit-tracker-frontend
spec:
  selector:
    app: habit-tracker-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort